#!/bin/bash

#   __ _                        ___ _
#  / _\ |_ ___  ___ _ __ ___   / _ (_)
#  \ \| __/ _ \/ _ \ '_ ` _ \ / /_)/ |
#  _\ \ ||  __/  __/ | | | | / ___/| |
#  \__/\__\___|\___|_| |_| |_\/    |_|
#
#
# This is the installation script for the SteemPi
#

if [ "$(id -u)" != "0" ]; then
   echo "Please use sudo to execute the installation. 'sudo ./install''" 1>&2
   exit 1
fi

./app/bash/install
